from dataclasses import dataclass
from typing import Literal


@dataclass(frozen=True)
class MarketEvent:
    """Represents an OHLCV market bar consumed by strategies and the engine.

    Attributes:
        timestamp: Bar timestamp (string for lightweight serialization).
        symbol: Instrument identifier (e.g., ``"NVDA"``).
        close: Closing price for the bar.
        open: Opening price for the bar. Defaults to ``close`` when omitted.
        high: High price for the bar. Defaults to ``close`` when omitted.
        low: Low price for the bar. Defaults to ``close`` when omitted.
        volume: Traded volume for the bar. Defaults to ``0.0`` when omitted.

    Example:
        >>> MarketEvent(timestamp="2024-01-02", symbol="NVDA", close=500.0)
        MarketEvent(timestamp='2024-01-02', symbol='NVDA', close=500.0, open=500.0, high=500.0, low=500.0, volume=0.0)
    """

    timestamp: str
    symbol: str
    close: float
    open: float | None = None
    high: float | None = None
    low: float | None = None
    volume: float | None = None

    def __post_init__(self) -> None:
        """Normalize optional fields for backward compatibility with close-only bars.

        Example:
            >>> event = MarketEvent(timestamp="t0", symbol="S", close=100.0)
            >>> (event.open, event.high, event.low, event.volume)
            (100.0, 100.0, 100.0, 0.0)
        """
        if self.open is None:
            object.__setattr__(self, "open", self.close)
        if self.high is None:
            object.__setattr__(self, "high", self.close)
        if self.low is None:
            object.__setattr__(self, "low", self.close)
        if self.volume is None:
            object.__setattr__(self, "volume", 0.0)


@dataclass(frozen=True)
class SignalEvent:
    """Strategy output indicating desired portfolio positioning.

    Attributes:
        timestamp: Signal timestamp.
        symbol: Symbol this signal targets.
        target_position: Desired exposure in ``[-1.0, +1.0]``.

    Example:
        >>> SignalEvent(timestamp="t1", symbol="S", target_position=0.5)
        SignalEvent(timestamp='t1', symbol='S', target_position=0.5)
    """

    timestamp: str
    symbol: str
    target_position: float  # -1.0 to +1.0


@dataclass(frozen=True)
class OrderEvent:
    """Execution instruction generated by the engine.

    Attributes:
        timestamp: Order creation time.
        symbol: Symbol to trade.
        side: Trade direction (``"BUY"`` or ``"SELL"``).
        quantity: Positive quantity in instrument units.
        order_type: ``"MARKET"``, ``"LIMIT"``, or ``"STOP"``.
        limit_price: Required for LIMIT orders.
        stop_price: Required for STOP orders.

    Example:
        >>> OrderEvent(timestamp="t1", symbol="S", side="BUY", quantity=10, order_type="LIMIT", limit_price=99)
        OrderEvent(timestamp='t1', symbol='S', side='BUY', quantity=10, order_type='LIMIT', limit_price=99, stop_price=None)
    """

    timestamp: str
    symbol: str
    side: Literal["BUY", "SELL"]
    quantity: float
    order_type: Literal["MARKET", "LIMIT", "STOP"] = "MARKET"
    limit_price: float | None = None
    stop_price: float | None = None


@dataclass(frozen=True)
class FillEvent:
    """Represents a completed execution returned by the broker simulation.

    Attributes:
        timestamp: Fill timestamp.
        symbol: Traded symbol.
        side: Fill direction.
        quantity: Filled quantity.
        fill_price: Execution price after spread/slippage assumptions.
        fee: Transaction fee charged for this fill.

    Example:
        >>> FillEvent(timestamp="t2", symbol="S", side="BUY", quantity=5, fill_price=101.0, fee=0.5)
        FillEvent(timestamp='t2', symbol='S', side='BUY', quantity=5, fill_price=101.0, fee=0.5)
    """

    timestamp: str
    symbol: str
    side: Literal["BUY", "SELL"]
    quantity: float
    fill_price: float
    fee: float
